# Generated by Django 5.2.2 on 2025-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genere',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genere',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('nepali', 'Nepali'), ('english', 'English'), ('hindi', 'Hindi')], max_length=20),
        ),
    ]
