# Generated by Django 5.2.2 on 2025-06-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genere_genre_rename_genere_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
