# Generated by Django 5.2.2 on 2025-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='Recommended_at',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
